### ISSUE TITLE
Nie zabijanie po kicku

### ISSUE THREAD

**Issue by Przemo12** [Inder00/iAntyLogout#1]
Mam propozycję, by nie zabijało gracza gdy wywali go się komendą /kick lub po wyrzuceniu przez nocheatplus

**Comment by Inder00** [comment]
Nie ma eventu odpowiedzialnego za nasłuchiwanie wyrzuconych graczy, wina nie leży po stronie pluginu. Może masz zainstalowany inny plugin/skrypt :)

**Comment by Przemo12** [comment]
mam plugin maxbans, i gdy wyrzuci gracza nocheatplus np za fly, antylogout zabija go...

**Comment by Inder00** [comment]
Jak mówię powyżej, nie ma nasłuchiwania wyrzuconych graczy, więc to nie jest wina pluginu.
![-ilnsalitdcichcpmnhtmg](https://user-images.githubusercontent.com/9884957/33036815-df29f970-ce2f-11e7-930b-d8e9af0906c5.png)

**Comment by Przemo12** [comment]
Ehh, nie wiem czy rozumiesz o co mi chodzi... Działa to tak, ze gracz jest podczaspvp, gdy wyjdzie z gry to zabija go, tak samo jest gdy się go kicknie lub antycheat to zrobi.... I to jest wina pluginu.
