### ISSUE TITLE
AntyLogout od perly oraz strzal

### ISSUE THREAD

**Issue by BakuQ** [Inder00/iAntyLogout#3]
Wprowadzenie w configu oraz w pluginie antylogouta od perly i strzal mozliwosc wlaczenia,wylaczenia

**Comment by Inder00** [comment]
Ale jaki to ma mieć sens i zastosowanie ? Gracz został zaatakowany to ma mieć antylogout

**Comment by BakuQ** [comment]
Serwery megadrop maja punche czyli strzelaja w siebie z luku i uciekaja szybko

**Comment by Inder00** [comment]
Jak dobrze pamiętam to jeżeli sam siebie gracz zaatakuje to nie ma antylogouta, jeżeli innego to wtedy oboje mają (włącznie ze śnieżką).
